version: '{build}'

branches:
  only:
    - master

skip_tags: true

init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: '12'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

build_script:
  - npm run build
  - echo build APPVEYOR_JOB_ID $APPVEYOR

test_script:
  - npm run test

on_finish:
  - sh: |
      echo finish APPVEYOR_JOB_ID $APPVEYOR_JOB_ID
  - ls -l
  # - curl -F 'file=@test-output.xml' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
