version: '{build}'

branches:
  only:
    - master

skip_tags: true

init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: '12'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

build_script:
  - npm run build:ci

test_script:
  - npm run test:ci

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-output.xml))
