version: '{build}'

branches:
  only:
    - master

skip_tags: true

init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: '12'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

build_script:
  - npm run build

test_script:
  - npm run test

on_finish:
  - echo $APPVEYOR_JOB_ID
  - ls -l
  - find "$APPVEYOR_BUILD_FOLDER" -type f -name 'test-output.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
